version: '3.8'

services:
  nococlone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nococlone_app
    ports:
      - "3000:3000"
    volumes:
      # Canal de persistencia local para la base de datos JSON y adjuntos subidos
      - ./nococlone_data:/app/data
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=tu_api_key_opcional
    restart: unless-stopped


